services:
  orca_backend:
    volumes:
      - .:/orca_backend
    restart: unless-stopped
    build: .
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      neo4j_url: neo4j
      CELERY_BROKER_URL: redis://redis:6379/0
    ports:
      - "8000:8000"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password  # Replace with your desired username/password
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs  # Updated to separate data and logs

  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    volumes:
      - ./redis:/data  # Changed to use relative path, adjust if needed

  celery:
    restart: unless-stopped
    build: .
    command: celery -A orca_backend worker --loglevel=info --pool=prefork --concurrency=1
    volumes:
      - .:/orca_backend
    depends_on:
      - neo4j
      - redis
      - orca_backend
    environment:
      neo4j_url: neo4j
      CELERY_BROKER_URL: redis://redis:6379/0

volumes:
  neo4j:
    driver: local
  redis:
    driver: local
