# device_ip(s) to start discovery with or subnet(s) separated by comma.
# After discovering the current device next  LLDP neighbour is discovered if any.
# Then move forward to next device in the network provided.
network: ["10.10.130.210"]
username: admin # username to make gNMI connection with device defined in network above
password: YourPaSsWoRd # password to make gNMI connection with device defined in network above
grpc_port: 8080 # port to make gNMI connection with device defined in network above
conn_timeout: 60 #connection timeout in seconds - used in - device ping , getting certificate and gnmi requests.

## Neo4j credentials used by orca_nw_lib
protocol: "bolt"
neo4j_url: "localhost:7687"
neo4j_user: "neo4j"
neo4j_password: "password"
