version: 1

handlers:
    file:
        class : logging.handlers.RotatingFileHandler
        formatter: format_1
        filename: ./orca.log
        maxBytes: 10485760 #10MB
        backupCount: 5
        level: INFO
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: format_1
        #args: (sys.stdout,)
    debug_console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: debug_format

formatters:
    format_1: 
        format: "[%(asctime)s][%(levelname)s][%(filename)s:%(lineno)d] %(message)s"
    debug_format:
        format: "[%(asctime)s][%(levelname)s][%(filename)s:%(lineno)d]:[%(threadName)s] %(message)s"

root:
    level: NOTSET
    #handlers: [console,file]
    #handlers: [debug_console]
    handlers: [console]
    propogate: yes