name: Build and Push Docker Image

# This workflow automates the building and pushing of Docker images for the orca_backend project.
# It is triggered by the following events:
# - Release creation: When a new release is created in the repository.
# - Push to main branch: When a push is made to the main branch.
# - Nightly build: Every day at midnight UTC.
on:
  release:
    types: [created]
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.STORDIS_DOCKER_HUB_USER }}
          password: ${{ secrets.STORDIS_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Generate Image Tag
        run: |
          if [[ ${{ github.event_name }} == 'release' ]]; then
            image_tag="${{ github.event.release.tag_name }}"
          elif [[ ${{ github.event_name }} == 'push' && ${{ github.ref }} == 'refs/heads/main' ]]; then
            image_tag="${{ github.sha }}-${{ github.event.head_commit.message }}"
            image_tag=$(echo "$image_tag" | cut -d' ' -f1 | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g')
          else
            nightly_build_number=$(( $(date +%j) % 10 ))
            image_tag="nightly-${nightly_build_number}"
          fi
          echo "Image Tag: $image_tag"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.STORDIS_DOCKER_HUB_USER }}/orca_backend:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.STORDIS_DOCKER_HUB_USER }}/orca_backend:latest
